//! The corpus blob the wasm head fits from — a compact, dependency-free
//! digest of the BLAKE3-pinned oracle fixture. Generated by
//! `bin/gen_corpus.rs` (which runs the FULL published recipe, including the
//! LOO λ selection) and committed; the native test regenerates the bytes and
//! requires identity, and re-runs the recipe against the recorded anchors.
//!
//! Layout (all little-endian):
//! ```text
//! "RFTC"            magic
//! u32  version      = 1
//! u32  n_options    design rows
//! u32  n_states     LOO units
//! f64  lambda       the recipe's selected λ (LOO over the pinned grid)
//! u32  in_anchor    in-corpus agreement at λ (Bench 881: 44)
//! u32  loo_anchor   LOO agreement at λ      (Bench 881: 44)
//! u32  offsets      (n_states+1) state row ranges
//! u8   argmaxes     n_states oracle decisions (lowest-index tie-break)
//! f64  targets      n_options oracle P(clean) per option
//! u8   raws         n_options × 5 decoded class ordinals
//! ```
//!
//! The wasm module reads the blob through [`BlobView`] — validation and
//! accessors over the raw bytes, no allocation. The owned [`Corpus`]
//! (Vec-backed) is host-only, for the generator and the tests; both paths
//! share [`BlobView::parse`] so there is exactly one validation.

pub const MAGIC: &[u8; 4] = b"RFTC";
pub const VERSION: u32 = 1;

/// The decoded feature width (per-option raws stride in the blob).
pub const F: usize = 5;

#[derive(Debug)]
pub struct Corrupt;

// ── the no_std view ──────────────────────────────────────────────────────

/// A validated view over the blob bytes — the wasm boot's only interface
/// to the corpus. Zero allocation: every accessor reads LE fields in place.
pub struct BlobView<'a> {
    bytes: &'a [u8],
    n_options: usize,
    n_states: usize,
    lambda: f64,
    in_anchor: u32,
    loo_anchor: u32,
    offsets_off: usize,
    argmaxes_off: usize,
    targets_off: usize,
    raws_off: usize,
}

fn u32_at(b: &[u8], off: usize) -> u32 {
    let s = [b[off], b[off + 1], b[off + 2], b[off + 3]];
    u32::from_le_bytes(s)
}

fn f64_at(b: &[u8], off: usize) -> f64 {
    let mut a = [0u8; 8];
    a.copy_from_slice(&b[off..off + 8]);
    f64::from_le_bytes(a)
}

impl<'a> BlobView<'a> {
    /// Parse + fully validate. Every later accessor is bounds-safe by
    /// construction after this succeeds.
    pub fn parse(bytes: &'a [u8]) -> Result<Self, Corrupt> {
        if bytes.len() < 32 || &bytes[..4] != MAGIC || u32_at(bytes, 4) != VERSION {
            return Err(Corrupt);
        }
        let n_options = u32_at(bytes, 8) as usize;
        let n_states = u32_at(bytes, 12) as usize;
        let lambda = f64_at(bytes, 16);
        let in_anchor = u32_at(bytes, 24);
        let loo_anchor = u32_at(bytes, 28);
        if !lambda.is_finite() || lambda <= 0.0 || n_states == 0 || n_options == 0 {
            return Err(Corrupt);
        }
        let mut off = 32usize;
        let mut need = |n: usize| -> Result<usize, Corrupt> {
            let at = off;
            off += n;
            if off > bytes.len() {
                Err(Corrupt)
            } else {
                Ok(at)
            }
        };
        let offsets_off = need((n_states + 1) * 4)?;
        let argmaxes_off = need(n_states)?;
        let targets_off = need(n_options * 8)?;
        let raws_off = need(n_options * F)?;
        // shape sanity: the offsets must cover exactly n_options rows
        if u32_at(bytes, offsets_off) != 0
            || u32_at(bytes, offsets_off + n_states * 4) as usize != n_options
        {
            return Err(Corrupt);
        }
        Ok(Self {
            bytes,
            n_options,
            n_states,
            lambda,
            in_anchor,
            loo_anchor,
            offsets_off,
            argmaxes_off,
            targets_off,
            raws_off,
        })
    }

    pub fn n_options(&self) -> usize {
        self.n_options
    }
    pub fn n_states(&self) -> usize {
        self.n_states
    }
    pub fn lambda(&self) -> f64 {
        self.lambda
    }
    pub fn in_anchor(&self) -> u32 {
        self.in_anchor
    }
    pub fn loo_anchor(&self) -> u32 {
        self.loo_anchor
    }

    pub fn offset(&self, state: usize) -> u32 {
        u32_at(self.bytes, self.offsets_off + state * 4)
    }
    /// All (n_states+1) offsets — the caller supplies the buffer.
    pub fn copy_offsets(&self, out: &mut [u32]) {
        for (i, o) in out.iter_mut().enumerate() {
            *o = self.offset(i);
        }
    }
    pub fn argmax(&self, state: usize) -> u8 {
        self.bytes[self.argmaxes_off + state]
    }
    pub fn copy_argmaxes(&self, out: &mut [u8]) {
        out.copy_from_slice(&self.bytes[self.argmaxes_off..self.argmaxes_off + self.n_states]);
    }
    pub fn target(&self, option: usize) -> f64 {
        f64_at(self.bytes, self.targets_off + option * 8)
    }
    /// All targets as f64 — the caller supplies the buffer.
    pub fn copy_targets(&self, out: &mut [f64]) {
        for (i, t) in out.iter_mut().enumerate() {
            *t = self.target(i);
        }
    }
    /// The raw ordinals as one contiguous slice (n_options × F).
    pub fn raws(&self) -> &'a [u8] {
        &self.bytes[self.raws_off..self.raws_off + self.n_options * F]
    }
}

// ── the owned form (host only: generator + tests) ────────────────────────

#[cfg(not(target_arch = "wasm32"))]
pub mod owned {
    use super::*;

    #[derive(Debug, Clone)]
    pub struct Corpus {
        pub lambda: f64,
        pub in_anchor: u32,
        pub loo_anchor: u32,
        pub n_options: usize,
        pub n_states: usize,
        pub offsets: Vec<u32>,
        pub argmaxes: Vec<u8>,
        pub targets: Vec<f64>,
        /// Per-option decoded class ordinals (5 per option, feature order).
        pub raws: Vec<u8>,
    }

    /// Parse to the owned form through the same [`BlobView::parse`]
    /// validation the wasm boot runs — one parser, two hosts.
    pub fn parse_owned(bytes: &[u8]) -> Result<Corpus, Corrupt> {
        let v = BlobView::parse(bytes)?;
        let mut offsets = vec![0u32; v.n_states + 1];
        v.copy_offsets(&mut offsets);
        let mut argmaxes = vec![0u8; v.n_states];
        v.copy_argmaxes(&mut argmaxes);
        let mut targets = vec![0.0f64; v.n_options];
        v.copy_targets(&mut targets);
        Ok(Corpus {
            lambda: v.lambda(),
            in_anchor: v.in_anchor(),
            loo_anchor: v.loo_anchor(),
            n_options: v.n_options(),
            n_states: v.n_states(),
            offsets,
            argmaxes,
            targets,
            raws: v.raws().to_vec(),
        })
    }

    pub fn write(
        lambda: f64,
        in_anchor: u32,
        loo_anchor: u32,
        offsets: &[u32],
        argmaxes: &[u8],
        targets: &[f64],
        raws: &[u8],
    ) -> Vec<u8> {
        let n_options = targets.len();
        let n_states = argmaxes.len();
        let mut out = Vec::with_capacity(32 + offsets.len() * 4 + n_states + n_options * 12);
        out.extend_from_slice(MAGIC);
        out.extend_from_slice(&VERSION.to_le_bytes());
        out.extend_from_slice(&(n_options as u32).to_le_bytes());
        out.extend_from_slice(&(n_states as u32).to_le_bytes());
        out.extend_from_slice(&lambda.to_le_bytes());
        out.extend_from_slice(&in_anchor.to_le_bytes());
        out.extend_from_slice(&loo_anchor.to_le_bytes());
        for o in offsets {
            out.extend_from_slice(&o.to_le_bytes());
        }
        out.extend_from_slice(argmaxes);
        for t in targets {
            out.extend_from_slice(&t.to_le_bytes());
        }
        out.extend_from_slice(raws);
        out
    }
}
