//! The arena's browser-live game heads — the engine's fitted game heads
//! compiled to WebAssembly so the latent-first lane plays in-tab with zero
//! engine.
//!
//! These are NOT second models: they are the engine's own published recipes
//! (standardize → ridge at the LOO-selected λ → linear score) re-run at
//! boot over the same digest-pinned oracle fixtures, as compact corpus
//! blobs. The fits are bit-identical to the native engine's — every op is a
//! correctly-rounded IEEE-754 f64 primitive with a pinned accumulation
//! order — and nothing is trusted without proof:
//!
//! - build time (`tests/recipe.rs`): each committed blob regenerates
//!   byte-identically, the full recipe (LOO λ selection included) hits the
//!   published anchors (tetris: Bench 881 λ=1, 44/120 + 44/120; flappy v3:
//!   Bench 882 λ=1, 96/100 + 96/100 + the full head digest), the grammars
//!   round-trip every corpus sentence, and the u8 standardizer equals the
//!   f64 one bit-for-bit;
//! - boot time (this module): each blob is re-validated and its fit is
//!   RE-RUN in the tab; if the in-corpus anchor does not reproduce, that
//!   head refuses and the page keeps the recorded demo for it;
//! - first play (JS probe): the tetris head must match every recorded
//!   (sentence → f32 P(clean)) pair of the demo's head game bit-exactly;
//!   the flappy head must reproduce its published 96/100 agreement over the
//!   corpus reel — before either board plays.
//!
//! ABI (all exports C-ABI, no wasm-bindgen, no allocator):
//! - `head_init() -> u32`        0 = ok (memoized; a per-head failure does
//!                               not take down the other head)
//! - `head_ready() -> u32`       ready MASK: bit0 = tetris, bit1 = flappy
//! - `head_lambda() -> f64`      the tetris recipe's λ
//! - `head_anchor() -> u32`      the verified tetris in-corpus agreement
//! - `head_flappy_lambda() -> f64` / `head_flappy_anchor() -> u32`
//! - `head_alloc(n) -> ptr`      16-aligned bump bytes (0 on OOM)
//! - `head_reset()`              rewind the bump pointer (single-threaded)
//! - `head_score(ptr, len) -> f64`   tetris P(clean); NaN = off-grammar
//! - `head_score_state(state_ptr, state_len, opt_ptr, opt_len) -> f64`
//!                               flappy P(clean) from (state, option)
//!                               sentences; NaN = off-grammar
//! - `memory`                    JS writes sentence bytes at alloc'd ptrs

#![cfg_attr(target_arch = "wasm32", no_std)]

pub mod boot;
pub mod corpus;
pub mod fit;
pub mod grammar;

#[cfg(not(target_arch = "wasm32"))]
pub mod gen;

/// The design widths (ungated — the wasm module pins its statics with
/// these; `gen` re-exports them host-side).
pub const TETRIS_F: usize = 5;
pub const TETRIS_D: usize = TETRIS_F + 1;
pub const FLAPPY_F: usize = 8;
pub const FLAPPY_D: usize = FLAPPY_F + 1;

// ── the wasm module ──────────────────────────────────────────────────────

#[cfg(target_arch = "wasm32")]
mod wasm {
    use core::arch::wasm32::{memory_grow, memory_size};
    use core::panic::PanicInfo;
    use core::ptr::{addr_of, addr_of_mut};

    use crate::boot::{self, BootPlan};
    use crate::corpus::BlobView;
    use crate::fit::{HeadFitter, Standardizer};
    use crate::{FLAPPY_D, FLAPPY_F, TETRIS_D, TETRIS_F};

    /// The committed corpus blobs — generated by `bin/gen_corpus.rs` from
    /// the digest-pinned fixtures and asserted by `tests/recipe.rs`.
    static TETRIS_BLOB: &[u8] = include_bytes!("tetris_corpus.bin");
    static FLAPPY_BLOB: &[u8] = include_bytes!("flappy_corpus.bin");

    /// The corpus shapes this build pins (each boot asserts equality — a
    /// future corpus regenerates the blob AND these consts together;
    /// `tests/recipe.rs` holds the same pins on the host side).
    const TETRIS_N_OPTIONS: usize = 2660;
    const TETRIS_N_STATES: usize = 120;
    const FLAPPY_N_OPTIONS: usize = 200;
    const FLAPPY_N_STATES: usize = 100;

    static mut TETRIS_ROWS: [[f64; TETRIS_D]; TETRIS_N_OPTIONS] =
        [[0.0; TETRIS_D]; TETRIS_N_OPTIONS];
    static mut TETRIS_TARGETS: [f64; TETRIS_N_OPTIONS] = [0.0; TETRIS_N_OPTIONS];
    static mut TETRIS_OFFSETS: [u32; TETRIS_N_STATES + 1] = [0; TETRIS_N_STATES + 1];
    static mut TETRIS_ARGMAXES: [u8; TETRIS_N_STATES] = [0; TETRIS_N_STATES];
    static mut TETRIS_HEAD: [f64; TETRIS_D] = [0.0; TETRIS_D];
    static mut TETRIS_STD: Option<Standardizer<TETRIS_F>> = None;
    static mut TETRIS_OK: bool = false;
    static mut TETRIS_IN_AGREE: u32 = 0;
    static mut TETRIS_LAMBDA: f64 = f64::NAN;

    static mut FLAPPY_ROWS: [[f64; FLAPPY_D]; FLAPPY_N_OPTIONS] =
        [[0.0; FLAPPY_D]; FLAPPY_N_OPTIONS];
    static mut FLAPPY_TARGETS: [f64; FLAPPY_N_OPTIONS] = [0.0; FLAPPY_N_OPTIONS];
    static mut FLAPPY_OFFSETS: [u32; FLAPPY_N_STATES + 1] = [0; FLAPPY_N_STATES + 1];
    static mut FLAPPY_ARGMAXES: [u8; FLAPPY_N_STATES] = [0; FLAPPY_N_STATES];
    static mut FLAPPY_HEAD: [f64; FLAPPY_D] = [0.0; FLAPPY_D];
    static mut FLAPPY_STD: Option<Standardizer<FLAPPY_F>> = None;
    static mut FLAPPY_OK: bool = false;
    static mut FLAPPY_IN_AGREE: u32 = 0;
    static mut FLAPPY_LAMBDA: f64 = f64::NAN;

    static mut BOOTED: bool = false;
    static mut BUMP: usize = 0;

    extern "C" {
        static __heap_base: u8;
    }

    #[panic_handler]
    fn panic(_: &PanicInfo) -> ! {
        // A panicking head is a broken build: halt. The page treats any
        // init/mask anomaly as "no wasm head" and keeps the recorded demo.
        loop {}
    }

    fn heap_base() -> usize {
        addr_of!(__heap_base) as usize
    }

    /// One head's boot: validate the blob, fill the statics, re-run the
    /// fit, verify the in-corpus anchor. Returns ok + the verified anchor.
    fn boot_one<const F: usize, const D: usize>(
        blob: &[u8],
        n_options: usize,
        n_states: usize,
        rows: &mut [[f64; D]],
        targets: &mut [f64],
        offsets: &mut [u32],
        argmaxes: &mut [u8],
    ) -> Result<(f64, u32, Standardizer<F>, [f64; D]), u32> {
        let v = BlobView::parse(blob).map_err(|_| 2u32)?;
        if v.n_options() != n_options
            || v.n_states() != n_states
            || v.feat_width() != F
        {
            return Err(3);
        }
        v.copy_targets(targets);
        v.copy_offsets(offsets);
        v.copy_argmaxes(argmaxes);
        let plan = BootPlan::<F, D> {
            n_options: v.n_options(),
            n_states: v.n_states(),
            lambda: v.lambda(),
            in_anchor: v.in_anchor(),
            offsets,
            argmaxes,
            targets,
            raws: v.raws(),
        };
        let mut fitter = HeadFitter::<D>::new();
        let out = boot::run(&plan, rows, &mut fitter).map_err(|e| match e {
            boot::BootErr::Anchor { .. } => 5u32,
            _ => 4u32,
        })?;
        Ok((plan.lambda, out.in_agree, out.std, out.w))
    }

    /// The shared boot sequence over this module's statics. A per-head
    /// failure degrades that head only (the page falls back per board).
    fn run_boot() {
        // Safety: single-threaded wasm — every export is driven by the one
        // JS thread; these statics are touched only here and in the score
        // exports.
        unsafe {
            let t = boot_one::<TETRIS_F, TETRIS_D>(
                TETRIS_BLOB,
                TETRIS_N_OPTIONS,
                TETRIS_N_STATES,
                &mut *addr_of_mut!(TETRIS_ROWS),
                &mut *addr_of_mut!(TETRIS_TARGETS),
                &mut *addr_of_mut!(TETRIS_OFFSETS),
                &mut *addr_of_mut!(TETRIS_ARGMAXES),
            );
            match t {
                Ok((lambda, agree, std, w)) => {
                    TETRIS_HEAD = w;
                    TETRIS_STD = Some(std);
                    TETRIS_IN_AGREE = agree;
                    TETRIS_LAMBDA = lambda;
                    TETRIS_OK = true;
                }
                Err(_) => TETRIS_OK = false,
            }
            let f = boot_one::<FLAPPY_F, FLAPPY_D>(
                FLAPPY_BLOB,
                FLAPPY_N_OPTIONS,
                FLAPPY_N_STATES,
                &mut *addr_of_mut!(FLAPPY_ROWS),
                &mut *addr_of_mut!(FLAPPY_TARGETS),
                &mut *addr_of_mut!(FLAPPY_OFFSETS),
                &mut *addr_of_mut!(FLAPPY_ARGMAXES),
            );
            match f {
                Ok((lambda, agree, std, w)) => {
                    FLAPPY_HEAD = w;
                    FLAPPY_STD = Some(std);
                    FLAPPY_IN_AGREE = agree;
                    FLAPPY_LAMBDA = lambda;
                    FLAPPY_OK = true;
                }
                Err(_) => FLAPPY_OK = false,
            }
            BOOTED = true;
        }
    }

    #[no_mangle]
    pub extern "C" fn head_init() -> u32 {
        unsafe {
            if !BOOTED {
                run_boot();
            }
            // 0 = both heads ok; 1 = partial; 2 = none (the page reads the
            // mask for the truth).
            let m = head_ready();
            if m == 3 {
                0
            } else if m == 0 {
                2
            } else {
                1
            }
        }
    }

    /// Ready MASK: bit0 = tetris, bit1 = flappy.
    #[no_mangle]
    pub extern "C" fn head_ready() -> u32 {
        unsafe {
            (TETRIS_OK as u32) | ((FLAPPY_OK as u32) << 1)
        }
    }

    #[no_mangle]
    pub extern "C" fn head_lambda() -> f64 {
        unsafe { TETRIS_LAMBDA }
    }

    #[no_mangle]
    pub extern "C" fn head_anchor() -> u32 {
        unsafe { TETRIS_IN_AGREE }
    }

    #[no_mangle]
    pub extern "C" fn head_flappy_lambda() -> f64 {
        unsafe { FLAPPY_LAMBDA }
    }

    #[no_mangle]
    pub extern "C" fn head_flappy_anchor() -> u32 {
        unsafe { FLAPPY_IN_AGREE }
    }

    /// 16-aligned bump allocation over linear memory (grows as needed).
    /// Returns 0 when growth is refused — the caller treats 0 as OOM.
    #[no_mangle]
    pub extern "C" fn head_alloc(n: u32) -> u32 {
        unsafe {
            if BUMP == 0 {
                BUMP = heap_base();
            }
            let ptr = (BUMP + 15) & !15usize;
            let end = ptr + n as usize;
            let pages = end.div_ceil(65536);
            let cur = memory_size(0);
            if pages > cur && memory_grow(0, pages - cur) == usize::MAX {
                return 0;
            }
            BUMP = end;
            ptr as u32
        }
    }

    /// Rewind the bump pointer — the JS score path calls this after each
    /// call (single-threaded by construction).
    #[no_mangle]
    pub extern "C" fn head_reset() {
        unsafe {
            BUMP = heap_base();
        }
    }

    /// P(clean) for one tetris spot sentence, or NaN when the sentence is
    /// not a well-formed spot sentence (the honest abstain — the engine's
    /// `respond` falls through the same way).
    #[no_mangle]
    pub extern "C" fn head_score(ptr: u32, len: u32) -> f64 {
        unsafe {
            if !TETRIS_OK {
                return f64::NAN;
            }
            let std = match *addr_of!(TETRIS_STD) {
                Some(s) => s,
                None => return f64::NAN,
            };
            let bytes = core::slice::from_raw_parts(ptr as *const u8, len as usize);
            let sentence = match core::str::from_utf8(bytes) {
                Ok(s) => s,
                Err(_) => return f64::NAN,
            };
            match boot::score_sentence(&std, &*addr_of!(TETRIS_HEAD), sentence) {
                Some(p) => p,
                None => f64::NAN,
            }
        }
    }

    /// P(clean) for one flappy (state, option) sentence pair, or NaN when
    /// either sentence is off-grammar.
    #[no_mangle]
    pub extern "C" fn head_score_state(
        state_ptr: u32,
        state_len: u32,
        opt_ptr: u32,
        opt_len: u32,
    ) -> f64 {
        unsafe {
            if !FLAPPY_OK {
                return f64::NAN;
            }
            let std = match *addr_of!(FLAPPY_STD) {
                Some(s) => s,
                None => return f64::NAN,
            };
            let sb = core::slice::from_raw_parts(state_ptr as *const u8, state_len as usize);
            let ob = core::slice::from_raw_parts(opt_ptr as *const u8, opt_len as usize);
            let (state, option) = match (core::str::from_utf8(sb), core::str::from_utf8(ob)) {
                (Ok(s), Ok(o)) => (s, o),
                _ => return f64::NAN,
            };
            match boot::score_flappy(&std, &*addr_of!(FLAPPY_HEAD), state, option) {
                Some(p) => p,
                None => f64::NAN,
            }
        }
    }
}
