//! The arena's browser-live Tetris head — the fitted game head compiled to
//! WebAssembly so the latent-first lane plays in-tab with zero engine.
//!
//! This is NOT a second model: it is the engine's own published recipe
//! (standardize → ridge at the LOO-selected λ → linear score) re-run over
//! the same BLAKE3-pinned oracle fixture, as a compact corpus blob. The fit
//! is bit-identical to the native engine's — every op is a correctly-rounded
//! IEEE-754 f64 primitive with a pinned accumulation order — and nothing is
//! trusted without proof:
//!
//! - build time (`tests/recipe.rs`): the committed blob regenerates
//!   byte-identically, the full recipe (LOO λ selection included) hits the
//!   published Bench 881 anchors (λ=1, 44/120 in-corpus, 44/120 LOO), the
//!   grammar round-trips every corpus sentence, and the u8-raw standardizer
//!   equals the f64 one bit-for-bit;
//! - boot time (this module): the blob is re-validated and the fit is
//!   RE-RUN in the tab; if the in-corpus anchor (44/120) does not
//!   reproduce, `head_init` refuses and the page keeps the recorded demo;
//! - first play (JS probe): every recorded (sentence → f32 P(clean)) pair
//!   of the demo's head game must match this module bit-exactly
//!   (`Math.fround` equality) before the board plays live.
//!
//! ABI (all exports C-ABI, no wasm-bindgen, no allocator):
//! - `head_init() -> u32`     0 = ready (memoized)
//! - `head_ready() -> u32`    1 after a successful init
//! - `head_lambda() -> f64`   the recipe's λ
//! - `head_anchor() -> u32`   the verified in-corpus agreement (44)
//! - `head_alloc(n) -> ptr`   16-aligned bump bytes (0 on OOM)
//! - `head_reset()`           rewind the bump pointer (single-threaded)
//! - `head_score(ptr, len) -> f64`  P(clean), or NaN when the sentence is
//!   off-grammar (the honest abstain — never a guess)
//! - `memory`                 JS writes sentence bytes at `head_alloc` ptrs

#![cfg_attr(target_arch = "wasm32", no_std)]

pub mod boot;
pub mod corpus;
pub mod fit;
pub mod grammar;

#[cfg(not(target_arch = "wasm32"))]
pub mod gen;

// ── the wasm module ──────────────────────────────────────────────────────

#[cfg(target_arch = "wasm32")]
mod wasm {
    use core::arch::wasm32::{memory_grow, memory_size};
    use core::panic::PanicInfo;
    use core::ptr::{addr_of, addr_of_mut};

    use crate::boot::{self, BootPlan};
    use crate::corpus::BlobView;
    use crate::fit::{HeadFitter, Standardizer, D};

    /// The committed corpus blob — generated by `bin/gen_corpus.rs` from
    /// the BLAKE3-pinned fixture and asserted by `tests/recipe.rs`.
    static BLOB: &[u8] = include_bytes!("tetris_corpus.bin");

    /// The corpus shape this build pins (the boot asserts equality — a
    /// future corpus regenerates the blob AND these two consts together;
    /// `tests/recipe.rs` holds the same pins on the host side).
    const N_OPTIONS: usize = 2660;
    const N_STATES: usize = 120;

    static mut ROWS: [[f64; D]; N_OPTIONS] = [[0.0; D]; N_OPTIONS];
    static mut TARGETS: [f64; N_OPTIONS] = [0.0; N_OPTIONS];
    static mut OFFSETS: [u32; N_STATES + 1] = [0; N_STATES + 1];
    static mut ARGMAXES: [u8; N_STATES] = [0; N_STATES];
    static mut HEAD: [f64; D] = [0.0; D];
    static mut STD: Option<Standardizer> = None;
    static mut STATE: u32 = 0; // 0 = not booted, 1 = ok, 2 = failed
    static mut IN_AGREE: u32 = 0;
    static mut LAMBDA: f64 = f64::NAN;
    static mut BUMP: usize = 0;

    extern "C" {
        static __heap_base: u8;
    }

    #[panic_handler]
    fn panic(_: &PanicInfo) -> ! {
        // A panicking head is a broken build: halt. The page treats any
        // non-zero init code as "no wasm head" and keeps the recorded demo.
        loop {}
    }

    fn heap_base() -> usize {
        addr_of!(__heap_base) as usize
    }

    /// The shared boot sequence over this module's statics.
    fn run_boot() -> u32 {
        let v = match BlobView::parse(BLOB) {
            Ok(v) => v,
            Err(_) => return 2,
        };
        if v.n_options() != N_OPTIONS || v.n_states() != N_STATES {
            return 3;
        }
        // Safety: single-threaded wasm — every export is driven by the one
        // JS thread; these statics are touched only here and in head_score.
        unsafe {
            let targets: &mut [f64] = &mut *addr_of_mut!(TARGETS);
            v.copy_targets(targets);
            let offsets: &mut [u32] = &mut *addr_of_mut!(OFFSETS);
            v.copy_offsets(offsets);
            let argmaxes: &mut [u8] = &mut *addr_of_mut!(ARGMAXES);
            v.copy_argmaxes(argmaxes);
            let plan = BootPlan {
                n_options: v.n_options(),
                n_states: v.n_states(),
                lambda: v.lambda(),
                in_anchor: v.in_anchor(),
                offsets,
                argmaxes,
                targets,
                raws: v.raws(),
            };
            let rows: &mut [[f64; D]] = &mut *addr_of_mut!(ROWS);
            let mut fitter = HeadFitter::new();
            let out = match boot::run(&plan, rows, &mut fitter) {
                Ok(r) => r,
                Err(_) => return 4,
            };
            HEAD = out.w;
            STD = Some(out.std);
            IN_AGREE = out.in_agree;
            LAMBDA = plan.lambda;
            STATE = 1;
        }
        0
    }

    #[no_mangle]
    pub extern "C" fn head_init() -> u32 {
        unsafe {
            if STATE == 1 {
                return 0;
            }
            if STATE == 2 {
                return 1;
            }
            STATE = 2;
        }
        let rc = run_boot();
        if rc == 0 {
            unsafe { STATE = 1 };
        }
        rc
    }

    #[no_mangle]
    pub extern "C" fn head_ready() -> u32 {
        unsafe { if STATE == 1 { 1 } else { 0 } }
    }

    #[no_mangle]
    pub extern "C" fn head_lambda() -> f64 {
        unsafe { LAMBDA }
    }

    #[no_mangle]
    pub extern "C" fn head_anchor() -> u32 {
        unsafe { IN_AGREE }
    }

    /// 16-aligned bump allocation over linear memory (grows as needed).
    /// Returns 0 when growth is refused — the caller treats 0 as OOM.
    #[no_mangle]
    pub extern "C" fn head_alloc(n: u32) -> u32 {
        unsafe {
            if BUMP == 0 {
                BUMP = heap_base();
            }
            let ptr = (BUMP + 15) & !15usize;
            let end = ptr + n as usize;
            let pages = end.div_ceil(65536);
            let cur = memory_size(0);
            if pages > cur && memory_grow(0, pages - cur) == usize::MAX {
                return 0;
            }
            BUMP = end;
            ptr as u32
        }
    }

    /// Rewind the bump pointer — the JS score path calls this after each
    /// sentence (single-threaded by construction).
    #[no_mangle]
    pub extern "C" fn head_reset() {
        unsafe {
            BUMP = heap_base();
        }
    }

    /// P(clean) for one spot sentence, or NaN when the sentence is not a
    /// well-formed spot sentence (the honest abstain — the engine's
    /// `respond` falls through the same way).
    #[no_mangle]
    pub extern "C" fn head_score(ptr: u32, len: u32) -> f64 {
        unsafe {
            if STATE != 1 {
                return f64::NAN;
            }
            let std = match *addr_of!(STD) {
                Some(s) => s,
                None => return f64::NAN,
            };
            let bytes = core::slice::from_raw_parts(ptr as *const u8, len as usize);
            let sentence = match core::str::from_utf8(bytes) {
                Ok(s) => s,
                Err(_) => return f64::NAN,
            };
            match boot::score_sentence(&std, &*addr_of!(HEAD), sentence) {
                Some(p) => p,
                None => f64::NAN,
            }
        }
    }
}
