// End-to-end protocol proof: replay the committed oracle fixture through the
// LIVE engine HTTP edge (lane=laya) and compare against the fixture's stored
// p_cleans (generated by the same RiirAgent forward, direct). Agreement here
// means the HTTP lane + mapping + grammar port reproduce the measured
// oracle. Also simulates lines-cleared for laya-argmax play.
// Run: node scripts/arena_protocol_check.mjs [fixture] [first_n_states]
import { readFileSync } from "node:fs";
import path from "node:path";

const FIXTURE =
  process.argv[2] ||
  path.resolve(import.meta.dirname, "../tests/fixtures/tetris_oracle_laya_en_v3.jsonl");
const N = Number(process.argv[3] ?? 8); // states to replay (2s/spot on a loaded box)

const ENGINE = process.env.REFLEX_ENGINE ?? "http://127.0.0.1:7331";
const QUESTION = "Does the stack look clean?";

async function pClean(sentence) {
  const r = await fetch(`${ENGINE}/decide`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "X-Reflex-Lane": "laya" },
    body: JSON.stringify({
      state: sentence,
      questions: [{ id: "q0", kind: "noul", prompt: QUESTION, options: [] }],
    }),
  });
  const j = await r.json();
  if (!r.ok) throw new Error(j.error);
  const a = j.answers[0];
  return a.outcome?.noul != null ? a.probabilities[0] : null;
}

const lines = readFileSync(FIXTURE, "utf8").split("\n").filter(Boolean);
let checked = 0;
let agree = 0;
let disagree = [];
let argmaxAgree = 0;
let argmaxTested = 0;

for (const line of lines) {
  const rec = JSON.parse(line);
  if (rec.state_id === "_meta") continue;
  if (checked >= N) break;
  checked += 1;
  const ps = [];
  for (const opt of rec.options) {
    ps.push(await pClean(opt.sentence));
  }
  // spot-level agreement (±0.02 — the fixture stores 4-rounded values from
  // the same forward; temperature is deterministic so agreement should be
  // near-exact)
  for (let i = 0; i < ps.length; i++) {
    const want = rec.options[i].p_clean;
    if (ps[i] != null && want != null && Math.abs(ps[i] - want) <= 0.02) agree += 1;
    else if (ps[i] != null && want != null) {
      disagree.push(`${rec.state_id}#${i}: live ${ps[i].toFixed(4)} vs fixture ${want}`);
    }
  }
  // decision-level agreement (lowest-index argmax)
  let live = -1, fix = -1, lp = -1, fp = -1;
  ps.forEach((p, i) => { if (p != null && p > lp) { lp = p; live = i; } });
  rec.options.forEach((o, i) => { if (o.p_clean != null && o.p_clean > fp) { fp = o.p_clean; fix = i; } });
  if (live >= 0 && fix >= 0) {
    argmaxTested += 1;
    if (live === fix) argmaxAgree += 1;
    else disagree.push(`${rec.state_id}: ARGMAX live ${live} vs fixture ${fix}`);
  }
  console.log(`  ${rec.state_id}: ${ps.length} spots, argmax live=${live} fixture=${fix}`);
}

console.log(`\nprotocol check: ${checked} states, ${agree} spot-level agreements`);
console.log(`decision argmax: ${argmaxAgree}/${argmaxTested}`);
if (disagree.length) {
  console.log(`disagreements (${disagree.length}):`);
  console.log(disagree.slice(0, 10).join("\n"));
  process.exit(1);
}
console.log("PASS");
