// The Reflexer (rulebook search) walk (katgpt-rs Issue 892 — the hybrid FSM champion,
// recorded by katgpt-rs examples/tetris_09_site_walk.rs) is checked here
// against the site's OWN pieces, shared by scripts/merge_rulebook_walk.mjs
// (before writing) and scripts/arena_demo_check.mjs (every run):
//
//   - stream — the walk's piece sequence equals the declared seed-607 stream,
//     regenerated by assets/games (PieceBag for "PieceBag(…", the recorder's
//     PIECES[u32Below(7)] for "PIECES[…");
//   - replay — from an EMPTY board, every record's board equals the replayed
//     board, its arity + state sentence equal buildTurn's, argmax(ps) (lowest
//     index on ties — the live boards' argmax) equals the recorded pick, the
//     ms array has one entry per option; replaying every pick reproduces the
//     summary's score / lines / tetrises / pieces exactly.
import assert from "node:assert/strict";
import * as T from "../assets/games/tetris.js";
import { Rng } from "../assets/games/rng.js";
import { PieceBag } from "../assets/games/tetris_view.js";

export const RULEBOOK_WALK_KEY = "tetris_rulebook_walk";
export const RULEBOOK_META_KEY = "tetris_rulebook";

function argmax(ps) {
  let best = -1;
  for (let i = 0; i < ps.length; i++) {
    if (ps[i] == null) continue;
    if (best === -1 || ps[i] > ps[best]) best = i;
  }
  return best;
}

/** The first `n` pieces of the declared stream (`meta.stream` prefix). */
export function streamPieces(stream, seed, n) {
  const rng = new Rng(seed);
  let draw;
  if (stream.startsWith("PieceBag(")) {
    const bag = new PieceBag(rng);
    draw = () => bag.next();
  } else if (stream.startsWith("PIECES[")) {
    draw = () => T.PIECES[rng.u32Below(7)];
  } else {
    throw new Error(`unknown rulebook stream: ${stream}`);
  }
  return Array.from({ length: n }, draw);
}

/** Throws on any drift; returns the replayed totals. */
export function verifyRulebookWalk(walk, meta, name = RULEBOOK_WALK_KEY) {
  assert.ok(Array.isArray(walk) && walk.length >= 10, `${name}: too short (${walk?.length})`);
  assert.ok(meta?.summary, `${name}: missing _meta.sources.${RULEBOOK_META_KEY}.summary`);
  const want = streamPieces(meta.stream, meta.seed, walk.length);
  const got = walk.map((r) => r[2]);
  assert.equal(got.join(""), want.join(""), `${name}: piece stream != ${meta.stream}`);

  const board = T.emptyBoard();
  let score = 0, lines = 0, tetrises = 0;
  for (let k = 0; k < walk.length; k++) {
    const [sentence, ps, piece, rows, pick, ms] = walk[k];
    const shown = T.fromStrings(rows);
    for (let r = 0; r < T.HEIGHT; r++) {
      for (let c = 0; c < T.WIDTH; c++) {
        assert.ok(board[r][c] === shown[r][c], `${name}[${k}]: board drift at (${r},${c})`);
      }
    }
    const opts = T.buildTurn(board, piece);
    assert.equal(opts.length, ps.length, `${name}[${k}]: arity ${ps.length} vs ${opts.length}`);
    assert.equal(opts[0].stateSentence, sentence, `${name}[${k}]: sentence drift`);
    assert.equal(ms?.length, ps.length, `${name}[${k}]: ms arity`);
    assert.ok(ms.every((x) => typeof x === "number" && x >= 0), `${name}[${k}]: ms values`);
    assert.ok(ps.every((p) => typeof p === "number" && p > 0 && p < 1), `${name}[${k}]: p outside (0,1)`);
    assert.equal(argmax(ps), pick, `${name}[${k}]: pick ${pick} is not argmax(ps)`);
    const cleared = T.commitPlacement(board, opts[pick]);
    lines += cleared;
    tetrises += cleared === 4 ? 1 : 0;
    score += [0, 40, 100, 300, 1200][Math.min(cleared, 4)];
  }
  const s = meta.summary;
  const replayed = { score, lines, pieces: walk.length, tetrises, decisions: walk.length };
  for (const [k, v] of Object.entries(replayed)) {
    assert.equal(s[k], v, `${name}: summary.${k} ${s[k]} vs replayed ${v}`);
  }
  assert.equal(s.abstains, 0, `${name}: the rulebook never abstains`);
  return replayed;
}
